{
  "backend_url": "https://selfhost-backend.example.com",
  "device_token_path": "/etc/evergreen/agent/secrets.json",
  "policy_cache_path": "/var/lib/evergreen/policy.json",
  "event_queue_path": "/var/lib/evergreen/events.json",
  "state_queue_path": "/var/lib/evergreen/state.json",
  "policy_public_key": "config/policy-public.pem",
  "enrollment": {
    "pre_shared_key": "",
    "config_path": ""
  },
  "intervals": {
    "policy_poll": "60s",
    "state_report": "5m",
    "event_flush": "30s",
    "retry_backoff": "15s",
    "retry_max_delay": "5m"
  },
  "logging": {
    "level": "info"
  }
}
